# do not create a queue: section for your test environment
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *common
  database: dairy_com 

test:
  <<: *common
  database: dairy_com_test
  
production:
  <<: *common
  database: dairy_com_production